### ISSUE TITLE
Error: write EPIPE in vscode terminal

### ISSUE THREAD

**Issue by enviroQL** [IlanCosman/tide#538]
#### Describe the bug

It's causing error outputs in the vscode terminal.
No issue when not using the theme.

#### Steps to reproduce

1. Open vscode terminal
2. Drag the terminal window for resizing
3. See error

```
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writeGeneric (node:internal/stream_base_commons:152:3)
    at Socket._writeGeneric (node:net:954:11)
    at Socket._write (node:net:966:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at console.value (node:internal/console/constructor:311:16)
    at console.log (node:internal/console/constructor:386:26)
    at Hr (file:///usr/share/code/resources/app/out/vs/code/node/cli.js:32:7200)
    at file:///usr/share/code/resources/app/out/vs/code/node/cli.js:32:11834
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (node:internal/streams/readable:1026:14)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v20.16.0
```

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.7.0
tide version: 6.1.1
term: xterm-256color
os: Linux Mint 22
terminal emulator: fish
fish startup: 430.04 millis
fisher plugins: jorgebucaran/fisher edc/bass ilancosman/tide@v6
```

**Comment by enviroQL** [comment]
found the error is from 

```
string match -q "$TERM_PROGRAM" "vscode"
and . (code --locate-shell-integration-path fish)
```

from the vscode instructions. if remove these two lines error disappears.
